#!/bin/bash
rm src/test/java/edu/utwente/vb/TestParserWithExamples.java
rm src/test/java/edu/utwente/vb/TestCheckerWithExamples.java

mvn clean test-compile
mvn exec:java -Dexec.mainClass=edu.utwente.vb.ParserTestGenerator -Dexec.classpathScope=test -e
mvn exec:java -Dexec.mainClass=edu.utwente.vb.CheckerTestGenerator -Dexec.classpathScope=test -e

